[build]
  command = "./build.sh"
  functions = "cmd/gateway"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "https://github.com/OlhaBalahush/web-forum"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/cmd/gateway/:splat"
  status = 200

[[functions]]
  name = "server"