[build]
  command = "go build ."
  functions = "functions"
  publish = "templates"

[build.environment]
  GO_IMPORT_PATH = "https://github.com/OlhaBalahush/web-forum"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200